### ISSUE TITLE
Pretty-Printing funApp horizontally swallows a comma

### ISSUE THREAD

**Issue by kaisucode** [bootstrapworld/pyret-blocks#16]
This line of code crashes the block editor when placed in beforehand as part of the example code in `example/editor-example.js`: 

`being(w.player.posn, radial-star(7, 1.5 * w.timer, 0.25 * w.timer, "solid", EXPLOSION-COLOR))`

The console prints out `Next token is ('NAME "radial-star") at 3:2-3:13`, and then a message of `TypeError: Cannot read property 'toString' of undefined` on CodeMirrorBlocks. 

However, the same line of code renders correctly with all the components and color schemes when manually inputted into the block editor.

**Comment by schanzer** [comment]
This actually looks like a pretty-printing issue. During a mode switch, CMB (1) parses the file, (2) pretty-prints it into a text representation that will be 1-to-1 with blocks, and (3) re-parses the pretty-printed code (see [these lines](https://github.com/bootstrapworld/codemirror-blocks/blob/master/src/ui/ToggleEditor.js#L160-L165)).

The fact that removing even a single character from various places makes the bug disappear makes me think that there's an off-by-one error happening somewhere.
