### ISSUE TITLE
No Drop Targets Visible (But Does Exist) On Hover for Blocks with Empty Bodies

### ISSUE THREAD

**Issue by maroon-scorch** [bootstrapworld/pyret-blocks#20]
For Blocks with Expandable Bodies such as Functions, Lambdas, etc. no drop targets are visible on them when hovering over:
![image](https://user-images.githubusercontent.com/71229054/107182950-603b0b00-69a3-11eb-886f-97a0070d7a9e.png)
Should be an easy fix

**Comment by schanzer** [comment]
The DOM is correct (if overly verbose). Looks like a CSS fix.

However, simplifying the DOM would make this a lot easier to debug - and given how slow the browser DOM is, make things just a tiny bit faster for large programs.

**Comment by schanzer** [comment]
Confirmed fixed. Thanks!
