### ISSUE TITLE
Minor Inconvenience in Vertical and Horizontal Scrolling using the Side Bar

### ISSUE THREAD

**Issue by maroon-scorch** [bootstrapworld/pyret-blocks#23]
Sometimes vertical scrollbars do not update in realtime:
![image](https://user-images.githubusercontent.com/71229054/107185360-efe2b880-69a7-11eb-97ee-4ae2a2ba1e47.png)
(^ The vertical scrollbar indicates it's at the end, but there's an entire block underneath)

Unless I proceed to click next to the block underneath, the bar does not update (and sometimes this might be inconsistent too).

We have some suspicion behind this being attributed to some inconsistencies between line size and block size, or how the line is displayed in the text editor vs how the block is displayed in the block editor.

(Note that the vertical scrolling issue can be easily resolved by scrolling down using the scrollbar of the mouse, I just happen to have a mouse with a broken scrollbar)

More pressingly, the same instance occurs with horizontal scrolling sometimes as well:
![image](https://user-images.githubusercontent.com/71229054/107185773-a6df3400-69a8-11eb-976f-abea3e2b1c2d.png)

One workaround could be to just fix the scrollbars or make them always appear.

**Comment by schanzer** [comment]
Does this happen even when the edit is _complete_, or only when the block is being dragged but not-yet-dropped?

**Comment by maroon-scorch** [comment]
Issue seems to have been fixed with block updates or so, at least they have no appeared again as an inconvenience.

**Comment by schanzer** [comment]
Yeah, the CMB library updates seem to have addressed this issue. Whew! Let's close.
